make -C burners\nand_sb\kickstart
make -C burners\nand_sb\nanderase
make -C burners\nand_sb\s1lapp
make -C kickstart\kickstart_sb_nand
make -C s1l\s1l_from_iram
make -C s1l\s1l_from_kick_full
copy burners\nand_sb\kickstart\*.bin .
copy burners\nand_sb\nanderase\*.bin .
copy burners\nand_sb\s1lapp\*.bin .
copy kickstart\kickstart_sb_nand\*.bin .
copy s1l\s1l_from_iram\*.bin .
copy s1l\s1l_from_kick_full\*.bin .
copy burners\nand_sb\kickstart\*.axf .
copy burners\nand_sb\nanderase\*.axf .
copy burners\nand_sb\s1lapp\*.axf .
copy kickstart\kickstart_sb_nand\*.axf .
copy s1l\s1l_from_iram\*.axf .
copy s1l\s1l_from_kick_full\*.axf .
copy burners\nand_sb\kickstart\*.elf .
copy burners\nand_sb\nanderase\*.elf .
copy burners\nand_sb\s1lapp\*.elf .
copy kickstart\kickstart_sb_nand\*.elf .
copy s1l\s1l_from_iram\*.elf .
copy s1l\s1l_from_kick_full\*.elf .
